### ISSUE TITLE
The module does works in my backoffice

### ISSUE THREAD

**Issue by FactoryBike** [blastanders/Prestashop-Resend-Order-Confirmation-Email#1]
Hello, i saw your module, i had install it ok, the module appears in modules section but in order summary dos not appear nothins to resend email new_order

¿Could you help me?

Thank´s and best regards

**Comment by FactoryBike** [comment]
Acabo de ver que ya funciona...solo que con los pedidos nuevos que me van saliendo.
Disculpa las molestias

**Comment by blastanders** [comment]
> Acabo de ver que ya funciona...solo que con los pedidos nuevos que me van saliendo. Disculpa las molestias

Hey, sorry for the late reply. Is this working in your shop now, or do you need my help?

**Comment by FactoryBike** [comment]
Hello @blastanders i had solve the insue. The problem was that in last update the "ES" folder disappeared. Now, all is fine. Thank´s for your feedback.
